name: Build packages

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: node_modules/.cache/turbo
        key: turbo-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: turbo-${{ github.ref_name }}-
    - name: Build packages
      shell: bash
      run: pnpm run build
