version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  pretest:
    steps:
      - run:
          name: Bootstrap
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build

executors:
  node:
    docker:
      - image: cimg/node:12.16

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
  unit-test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - node/install-packages
      - pretest
      - run:
          name: Unit tests
          command: npm run test:unit -- --coverage --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit
      - store_test_results:
          path: reports/junit
      - run:
          name: Upload coverage
          command: npm run codecov
  integration-test:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - pretest
      - run:
          name: Integration tests
          command: npm run test:integration -- --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit
      - store_test_results:
          path: reports/junit

workflows:
  version: 2
  test:
    jobs:
      - lint
      - unit-test:
          matrix:
            parameters:
              node-version: ["8.17", "10.20", "12.16"]
          requires:
            - lint
      - integration-test:
          requires:
            - lint
