name: Test
on:
  push:
  pull_request:

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  PNPM_VERSION: 5.17.2

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set pnpm store dir
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: Lint files
        run: pnpm run lint
  test:
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ matrix.node-version }}-
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set pnpm store dir
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      # https://github.com/actions/virtual-environments/issues/712#issuecomment-613004302
      - name: Set TEMP on Windows
        run: echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        if: ${{ runner.os == 'Windows' }}
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Run unit tests
        run: pnpm run test:unit -- --coverage
      - name: Run integration tests
        run: pnpm run test:integration
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
