name: Test
on:
  push:
  pull_request:

env:
  PNPM_VERSION: 7.12.1
  HELM_VERSION: 3.5.3
  KUSTOMIZE_VERSION: 4.4.1

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: Lint files
        run: pnpm run lint
  test:
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      # https://github.com/actions/virtual-environments/issues/712#issuecomment-613004302
      - name: Set TEMP on Windows
        run: echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        if: ${{ runner.os == 'Windows' }}
      - uses: azure/setup-kubectl@v1
        with:
          version: v1.23.1
      - name: Install Helm
        run: |
          if [ $RUNNER_OS = 'Windows' ]; then
            export HELM_INSTALL_DIR=/c/Windows
          fi

          curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -s -- --version v${{ env.HELM_VERSION }} --no-sudo
        shell: bash
      - name: Install Kustomize
        run: |
          bin_path=/usr/local/bin

          if [ $RUNNER_OS = 'Windows' ]; then
            bin_path=/c/Windows
          fi

          rm -rf $bin_path/kustomize
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/kustomize/v${{ env.KUSTOMIZE_VERSION }}/hack/install_kustomize.sh | bash -s -- ${{ env.KUSTOMIZE_VERSION }} $bin_path
        shell: bash
      - name: Run unit tests
        run: pnpm run test:unit --coverage
      - name: Run integration tests
        run: pnpm run test:integration
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-browser:
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: Run browser tests
        run: pnpm run test:browser
